#!/bin/bash

echo "Welcome to the World of Tomorrow!"

firstline=$(head -n 1 source/changelog.md)
read -a splitfirstline <<< $firstline
version=${splitfirstline[1]}
echo "You are building version" $version
echo "Do you want to continue? (enter '1' for yes or '0' for no)"
read versioncontinue
if [ $versioncontinue -eq 1 ]
then
  echo "OK"
else
  echo "Please come back when you are ready"
fi
